### ISSUE TITLE
processing v1.1

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/rema.proc#3]
# TODO

- [x] process all 8m tiles for rock presence
- [x] process all 200m and 100m tiles, fill, slope, aspect, rugosity
- [x] process all 200m and 100m tiles for rock class ~(gdalwarp with 'max' ?)~ fasterize at res
- [x] check grid alignment
- [x] check coverage, file sanity
- [x] create untiled versions of 100m and 200m fill, slope, aspect, rugosity
- [x] process rock covered 8m tiles for fill, slope, aspect, rugosity
- [x] create raadfiles index of all processed tiles, by resolution, variable, tile-finders etc. 
- [x] ~create VRT generators for processed tiles (GDAL handles the overlapping margins)~
- [x] ~tile generators, for 8m, 100m, 200m that include all the file paths in one with tile polygon and raster-gen command ~
- [x] check everything in detail

see gdalio for better read https://github.com/hypertidy/gdalio

**Comment by mdsumner** [comment]
Here's generating filled tiles for 100m and 200m (still sanity checking so it's saving locally not in the file share yet)

TODO

- [ ] ensure right resample algorithm for gdalwarp
- [ ] thoughts towards remosacking? 


```R
rema_rock_raster_files <- function() {
  library(dplyr)
  raadfiles::get_raad_filenames(all = TRUE) %>%
    dplyr::filter(grepl("data_local", root)) %>%
    dplyr::filter(grepl(".*v1.1.*_8m_rock.tif", file)) %>%
    dplyr::transmute(fullname = file.path(root, file))
}
rema_rock_raster_files <- memoise::memoize(rema_rock_raster_files)

library(raster)

rfiles <- rema_rock_raster_files()
ext_to_te <- function(x) {
  x <- extent(x) + 200
  sprintf("-te %f %f %f %f", raster::xmin(x), raster::ymin(x), 
                            raster::xmax(x), raster::ymax(x))
}

ext_to_te100 <- function(x) {
  x <- extent(x) + 100
  sprintf("-te %f %f %f %f", raster::xmin(x), raster::ymin(x), 
          raster::xmax(x), raster::ymax(x))
}
res_to_tr <- function(x) {
  sprintf("-tr %f %f", raster::res(x)[1], raster::res(x)[2])
}
get_tile <- function(i) {
  raster::crop(raster::raster(raadfiles::rema_200m_files()$fullname), raster::raster(rfiles$fullname[i]))
}
geoidfile <- "/perm_storage/home/mdsumner/Git/potato/inst/extdata/geoid15.tif"
srcfiles <- c(raadfiles::rema_200m_files()$fullname, 
              geoidfile, raadfiles::rema_100m_files()$fullname)


for (i in 1:nrow(rfiles)) {
#  writeLines(sf::st_crs("EPSG:3031")$wkt, "srs_def")
  out.tif <- file.path("200m", gsub("_rock", "_filled_geoid", basename(rfiles$fullname[i])))
  #unlink(out.tif)
  g <- glue::glue("gdalwarp {srcfiles[2]} {srcfiles[1]} {ext_to_te100(get_tile(i))} {res_to_tr(raster::raster(srcfiles[1]))} -t_srs srs_def  {out.tif} -co COMPRESS=DEFLATE")
  system(g)
#  plot(raster(out.tif))
}



for (i in 1:nrow(rfiles)) {
  #writeLines(sf::st_crs("EPSG:3031")$wkt, "srs_def")
  out.tif <- file.path("100m", gsub("8m_rock", "100m_filled_geoid", basename(rfiles$fullname[i])))
  #unlink(out.tif)
  g <- glue::glue("gdalwarp {srcfiles[2]} {srcfiles[1]} {srcfiles[3]} {ext_to_te(get_tile(i))} {res_to_tr(raster::raster(srcfiles[3]))} -t_srs srs_def  {out.tif} -co COMPRESS=DEFLATE")
  system(g)
#  plot(raster(out.tif))
}



```

**Comment by mdsumner** [comment]
use gdalwarp for the 100m,200m rock or just fasterize again? 

extent: -2337400, -2323700, 1050308, 1060892 

gdalwarp -r max 

![image](https://user-images.githubusercontent.com/4107631/123028879-7a8df680-d423-11eb-93e8-3a2441f4cac3.png)



probably just use fasterize ....

**Comment by mdsumner** [comment]
Example, bundle up the 100m in a VRT and plot a quick overview

```R
raadroot <- "/rdsi/PRIVATE/raad2/data_local/aad.gov.au/rema/processing/v1.1"
files <- tibble::tibble(fullname = fs::dir_ls(file.path(raadroot, "100m"), regexp = "rugosity.*tif$", recurse = TRUE))

writeLines(files$fullname, "filelist")
system("gdalbuildvrt -input_file_list filelist rugosity_100m.vrt")
raster::raster("rugosity_100m.vrt")
class      : RasterLayer 
dimensions : 45002, 55002, 2475200004  (nrow, ncol, ncell)
resolution : 100, 100  (x, y)
extent     : -2700100, 2800100, -2200100, 2300100  (xmin, xmax, ymin, ymax)
crs        : +proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs 
source     : rugosity_100m.vrt 
names      : rugosity_100m 

```

the warper will be faster and upfront convert to a new file (possibly cropped ...) is preferred

**Comment by mdsumner** [comment]
quick zoom check

![image](https://user-images.githubusercontent.com/4107631/123056428-411cb180-d44a-11eb-9710-ccc4119067e6.png)


![image](https://user-images.githubusercontent.com/4107631/123056594-66a9bb00-d44a-11eb-9a75-858b33b50cc2.png)


![image](https://user-images.githubusercontent.com/4107631/123056653-76c19a80-d44a-11eb-97f0-c41f2ea10018.png)
